# Dataset :- 1

In [2]:
import numpy as np

In [3]:
print('1-length,2-diameter,3-height,4-weight,5-shucked weight,6-viscera weight,7-shell weight,8-age')
a=np.genfromtxt(r"C:\Users\hithe\Downloads\train_extended.csv",delimiter=',',skip_header=1)
a

1-length,2-diameter,3-height,4-weight,5-shucked weight,6-viscera weight,7-shell weight,8-age


array([[ 1.575     ,  1.225     ,  0.375     , ...,  6.3219385 ,
         9.63883   , 10.        ],
       [ 1.2375    ,  1.        ,  0.375     , ...,  3.798833  ,
         7.654365  , 19.        ],
       [ 1.45      ,  1.1625    ,  0.4125    , ...,  7.01650125,
         7.257472  , 11.        ],
       ...,
       [ 1.125     ,  0.9125    ,  0.2875    , ...,  1.984465  ,
         3.118445  ,  7.        ],
       [ 1.625     ,  1.275     ,  0.4125    , ...,  7.86698625,
        10.489315  , 11.        ],
       [ 1.5875    ,  1.25      ,  0.3875    , ...,  7.38504475,
         8.788345  , 11.        ]])

## 1) what is the min and max of length column

In [4]:
maxi=np.max(a[:,0])
mini=np.min(a[:,0])
print(maxi)
print(mini)

7.58349125
0.0


## 2) Difference between the max and min length of the length coloumn

In [78]:
print(maxi-mini)

7.58349125


## 3) Find coloumn wise age

In [79]:
a[:,7]

array([10., 19., 11., ...,  7., 11., 11.])

# 4) Find out all the age whose height is greater than 0.4 

In [80]:
a1=a[a[:,2]>0.4]
a1[:,7]

array([11., 14., 13., ..., 11., 11., 11.])

## 5) what is the avg weight and height of whose age is 10 

In [81]:
a2=a[a[:,7]==10]
avg_hei=a2[:,2]
avg_wei=a2[:,3]
print('Average height is:- ',np.mean(avg_hei),'\n')
print('Average weight is:- ',np.mean(avg_wei))

Average height is:-  0.3833672856539947 

Average weight is:-  28.243308450511314


## 6) What is total of shell weight

In [82]:
np.sum(a[:,6])

1326845.8295214002

## 7) How many persons belong to each and every unique age

In [83]:
np.unique(a[:,7],return_counts=True)

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
        27., 29.]),
 array([   46,    42,   625,  2787,  5475, 12450, 18276, 26818, 32906,
        30803, 23457, 12717, 10037,  6352,  4831,  3191,  2705,  1953,
         1591,  1206,   721,   296,   352,   110,    51,    46,    99,
           57], dtype=int64))

## 8) What is the difference between shucked weight and viscera weight

In [84]:
a[:,4]-a[:,5]

array([5.9817445, 3.855532 , 4.1106775, ..., 2.9199985, 5.329706 ,
       9.8372765])

## 9) What is average height of the persons whose age is between 14 and 19

In [85]:
a3=(a[:,7]>=14) & (a[:,7]<=19)
np.mean(a3)

0.103115

## 10) What is the average weight if we include shucked weight and viscera weight and shell weight

In [6]:
a4=a[:,4]+a[:,5]+a[:,6]
np.mean(a4)

21.616780352404746

# Dataset :- 2

In [22]:
print('1-total_bill,2-tip,3-sex,4-smoker,5-day,6-time,7-size')
b=np.genfromtxt(r"C:\Users\hithe\Downloads\tipsf.csv",delimiter=',',skip_header=1)
b

1-total_bill,2-tip,3-sex,4-smoker,5-day,6-time,7-size


array([[  0.  ,  16.99,   1.01, ...,   1.  ,   0.  ,   2.  ],
       [  1.  ,  10.34,   1.66, ...,   1.  ,   0.  ,   3.  ],
       [  2.  ,  21.01,   3.5 , ...,   1.  ,   0.  ,   3.  ],
       ...,
       [241.  ,  22.67,   2.  , ...,   0.  ,   0.  ,   2.  ],
       [242.  ,  17.82,   1.75, ...,   0.  ,   0.  ,   2.  ],
       [243.  ,  18.78,   3.  , ...,   2.  ,   0.  ,   2.  ]])

## 1) What is the total bill value

In [23]:
np.sum(b[:,1])

4827.77

## 2) What is the total tip value

In [24]:
np.sum(b[:,2])

731.5799999999999

## 3) count how many sunday,saturday,thursdays,fridays are there

In [70]:
np.unique(b[:,5],return_counts=True)

(array([0., 1., 2., 3.]), array([87, 76, 62, 19], dtype=int64))

## 4) How many smokers are there

In [38]:
np.unique(b[:,4],return_counts=True)

(array([0., 1.]), array([151,  93], dtype=int64))

## 5) What is the avg tip given by male and female

In [61]:
b1=b[b[:,3]!=0] #male
b2=b[b[:,3]==0] #female
print('Avg tip given by male:- ',np.mean(b1[:,2]))
print('Avg tip given by female:- ',np.mean(b2[:,2]))

Avg tip given by male:-  3.0896178343949043
Avg tip given by female:-  2.8334482758620685


## 6) How much amount have been spent by male and female

In [66]:
print('Amount have been spent by male:- ',np.sum(b1[:,1]),'\n')
print('Amount have been spent by female:- ',np.sum(b2[:,1]))

Amount have been spent by male:-  3256.8199999999997 

Amount have been spent by female:-  1570.9499999999996


## 7) What is the min and max tip given

In [69]:
print('min tip:- ',np.min(b[:,2]))
print('max tip:- ',np.max(b[:,2]))

min tip:-  1.0
max tip:-  10.0


## 8) How many male and females are going for lunch and dinner 

## 9) Find out the avg size

In [71]:
np.mean(b[:,7])

2.569672131147541

## 10) How many female smokers are there and males are there 

In [98]:
print('Count of Male smokers are:- ',len(b1[b1[:,4]==1]))
print('Counr of female smokers are:- ',len(b2[b2[:,4]==1]))

Count of Male smokers are:-  60
Counr of female smokers are:-  33
